# Generated by Django 5.1.9 on 2025-05-27 22:06

import clickhouse_backend.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', clickhouse_backend.models.StringField()),
                ('fecha', clickhouse_backend.models.DateTime64Field(auto_now_add=True)),
            ],
            options={
                'db_table': 'prueba_conexion',
                'engine': clickhouse_backend.models.MergeTree(order_by=('fecha',)),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
