# Generated by Django 5.2.1 on 2025-05-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ShiftDate", models.TextField()),
                ("Shift", models.CharField(max_length=255)),
                ("Shovel", models.CharField(max_length=255)),
                ("ShovelModel", models.CharField(max_length=255)),
                ("Equipment", models.CharField(max_length=255)),
                ("TruckFleet", models.CharField(max_length=255)),
                ("LoadingZone", models.CharField(max_length=255)),
                ("Material", models.CharField(max_length=255)),
                ("MeasuredTonnage", models.FloatField()),
                ("ReportedTonnage", models.FloatField()),
                ("DestinationType", models.CharField(max_length=255)),
                ("Destination", models.CharField(max_length=255)),
                ("TravelingEmpty", models.FloatField()),
                ("E_TravelingStart", models.DateTimeField()),
                ("E_TravelingEnd", models.DateTimeField()),
                ("WaitingEmpty", models.FloatField()),
                ("E_WaitingStart", models.DateTimeField()),
                ("E_WaitingEnd", models.DateTimeField()),
                ("SpottingEmpty", models.FloatField()),
                ("E_SpottingStart", models.DateTimeField()),
                ("E_SpottingEnd", models.DateTimeField()),
                ("LoadingMaterial", models.FloatField()),
                ("E_LoadingStart", models.DateTimeField()),
                ("E_LoadingEnd", models.DateTimeField()),
                ("Hauling", models.FloatField()),
                ("L_HaulingStart", models.DateTimeField()),
                ("L_HaulingEnd", models.DateTimeField()),
                ("WaitingLoad", models.FloatField()),
                ("L_WaitingStart", models.DateTimeField()),
                ("L_WaitingEnd", models.DateTimeField()),
                ("SpottingLoad", models.FloatField()),
                ("L_SpottingStart", models.DateTimeField()),
                ("L_SpottingEnd", models.DateTimeField()),
                ("UnloadingMaterial", models.FloatField()),
                ("L_UnloadingStart", models.DateTimeField()),
                ("L_UnloadingEnd", models.DateTimeField()),
                ("DistanceEmpty", models.FloatField()),
                ("DistanceLoaded", models.FloatField()),
                ("G_Latitude", models.FloatField()),
                ("G_Longitude", models.FloatField()),
                ("G_Elevation", models.FloatField()),
                ("D_Latitude", models.FloatField()),
                ("D_Longitude", models.FloatField()),
                ("D_Elevation", models.FloatField()),
                ("EquivalentDistance", models.FloatField()),
                ("TotalCycleTime", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="FuelSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Veh", models.CharField(max_length=255)),
                ("Descripcion", models.CharField(max_length=255)),
                ("fin_desp", models.DateTimeField()),
                ("volumCorregido", models.FloatField()),
                ("Origin", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ShiftDate", models.TextField()),
                ("Shift", models.CharField(max_length=255)),
                ("TimeStamp", models.DateTimeField()),
                ("RecordDuration", models.FloatField()),
                ("Equipment", models.CharField(max_length=255)),
                ("TruckFleet", models.CharField(max_length=255)),
                ("FuelLevel", models.FloatField()),
                ("FuelLevelLiters", models.FloatField()),
                ("FuelGauge", models.CharField(max_length=255)),
                ("Speed", models.FloatField()),
                ("RPM", models.FloatField()),
                ("Ralenti", models.CharField(max_length=255)),
                ("Latitude", models.FloatField()),
                ("Longitude", models.FloatField()),
                ("Elevation", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TimeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ShiftDate", models.TextField()),
                ("Shift", models.CharField(max_length=255)),
                ("TimeStamp", models.DateTimeField()),
                ("RecordDuration", models.FloatField()),
                ("Equipment", models.CharField(max_length=255)),
                ("TruckFleet", models.CharField(max_length=255)),
                ("Status", models.CharField(max_length=255)),
                ("Category", models.CharField(max_length=255)),
                ("Event", models.CharField(max_length=255)),
            ],
        ),
    ]
